from __future__ import annotations

import pandas as pd


COLUMN_LABELS = {
    "run_date": "判定日",
    "screen_version": "スクリーナー版",
    "generated_at": "生成日時",
    "rank": "監視順位",
    "ticker": "ティッカー",
    "name": "銘柄名",
    "score": "総合スコア",
    "trend_score": "トレンドスコア",
    "quality_score": "業績スコア",
    "strength_score": "強さスコア",
    "close": "終値",
    "turnover_million": "売買代金(百万円)",
    "market_cap_billion": "時価総額(十億円)",
    "revenue_growth_pct": "売上成長率(%)",
    "profit_margin_pct": "利益率(%)",
    "roe_pct": "ROE(%)",
    "current_ratio": "流動比率",
    "debt_to_equity": "D/Eレシオ",
    "change_20d_pct": "20日騰落率(%)",
    "change_60d_pct": "60日騰落率(%)",
    "change_120d_pct": "120日騰落率(%)",
    "gap_to_52w_high_pct": "52週高値差(%)",
    "volume_ratio_20": "出来高倍率(20日)",
    "ma25_slope_pct": "25日線傾き(%)",
    "ma75_slope_pct": "75日線傾き(%)",
    "ma200_slope_pct": "200日線傾き(%)",
    "ma25_above_ma200": "25日線>200日線",
    "ma75_above_ma200": "75日線>200日線",
    "ma25_above_ma75": "25日線>75日線",
    "perfect_order": "PO(25>75>200)",
    "bearish_stack_recent": "逆並び履歴あり",
    "bearish_perfect_order_recent": "逆PO履歴あり",
    "ma25_cross_200_today": "25日GC200(当日)",
    "ma75_cross_200_today": "75日GC200(当日)",
    "ma25_cross_200_recent": "25日GC200(直近)",
    "ma75_cross_200_recent": "75日GC200(直近)",
    "ma25_cross_75_today": "25日GC75(当日)",
    "ma25_cross_75_recent_tight": "25日GC75(直近)",
    "ma25_cross_200_recent_tight": "25日GC200(直近厳選)",
    "ma75_cross_200_recent_tight": "75日GC200(直近厳選)",
    "perfect_order_today": "PO形成(当日)",
    "perfect_order_recent_tight": "PO形成(直近厳選)",
    "perfect_order_recent": "PO形成(直近)",
    "initial_trend_signal": "初動75GC200シグナル",
    "early_reversal_setup": "逆PO転換準備",
    "reversal_from_bearish_po": "逆PO→上昇PO転換",
    "days_since_75gc200": "75日GC200からの日数",
    "days_since_perfect_order": "PO形成からの日数",
    "close_vs_ma25_pct": "25日線乖離(%)",
    "close_vs_ma75_pct": "75日線乖離(%)",
    "close_vs_ma200_pct": "200日線乖離(%)",
    "touch_ma25_intraday": "25日線タッチ",
    "touch_ma75_intraday": "75日線タッチ",
    "reclaim_ma25_close": "25日線上で引け",
    "reclaim_ma75_close": "75日線上で引け",
    "failed_ma25_reclaim": "25日線戻せず",
    "failed_ma75_reclaim": "75日線戻せず",
    "support_reaction_ok": "支持反応OK",
    "ma25_pullback_candidate": "25日押し目候補",
    "ma75_pullback_candidate": "75日押し目候補",
    "down_volume_spike": "下落出来高急増",
    "pullback_score": "押し目スコア",
    "pullback_candidate": "押し目候補シグナル",
    "sector": "セクター",
    "industry": "業種",
}

WATCHLIST_LATEST_COLUMN_ORDER = [
    "判定日",
    "監視順位",
    "ティッカー",
    "銘柄名",
    "逆PO→上昇PO転換",
    "逆PO転換準備",
    "初動75GC200シグナル",
    "押し目候補シグナル",
    "押し目スコア",
    "PO形成からの日数",
    "PO形成(直近)",
    "25日GC75(直近)",
    "25日GC200(直近厳選)",
    "75日GC200(直近厳選)",
    "総合スコア",
    "トレンドスコア",
    "業績スコア",
    "強さスコア",
    "終値",
    "売買代金(百万円)",
    "時価総額(十億円)",
    "売上成長率(%)",
    "利益率(%)",
    "ROE(%)",
    "20日騰落率(%)",
    "60日騰落率(%)",
    "52週高値差(%)",
    "出来高倍率(20日)",
    "25日線タッチ",
    "75日線タッチ",
    "25日線上で引け",
    "75日線上で引け",
    "25日線戻せず",
    "75日線戻せず",
    "支持反応OK",
    "25日押し目候補",
    "75日押し目候補",
    "下落出来高急増",
    "25日線傾き(%)",
    "75日線傾き(%)",
    "セクター",
    "業種",
]

WATCHLIST_HISTORY_COLUMN_ORDER = [
    "判定日",
    "監視順位",
    "ティッカー",
    "銘柄名",
    "逆PO→上昇PO転換",
    "逆PO転換準備",
    "初動75GC200シグナル",
    "押し目候補シグナル",
    "押し目スコア",
    "PO形成からの日数",
    "逆PO履歴あり",
    "PO形成(直近)",
    "PO形成(当日)",
    "PO形成(直近厳選)",
    "25日GC75(直近)",
    "25日GC200(直近厳選)",
    "75日GC200(直近厳選)",
    "総合スコア",
    "トレンドスコア",
    "業績スコア",
    "強さスコア",
    "終値",
    "売買代金(百万円)",
    "時価総額(十億円)",
    "売上成長率(%)",
    "利益率(%)",
    "ROE(%)",
    "20日騰落率(%)",
    "60日騰落率(%)",
    "52週高値差(%)",
    "出来高倍率(20日)",
    "25日線タッチ",
    "75日線タッチ",
    "25日線上で引け",
    "75日線上で引け",
    "25日線戻せず",
    "75日線戻せず",
    "支持反応OK",
    "25日押し目候補",
    "75日押し目候補",
    "下落出来高急増",
    "25日線傾き(%)",
    "75日線傾き(%)",
    "200日線乖離(%)",
    "25日線>75日線",
    "25日線>200日線",
    "75日線>200日線",
    "PO(25>75>200)",
    "逆並び履歴あり",
    "25日GC75(当日)",
    "25日GC200(当日)",
    "75日GC200(当日)",
    "セクター",
    "業種",
]

GC_WATCHLIST_COLUMN_ORDER = [
    "判定日",
    "監視順位",
    "ティッカー",
    "銘柄名",
    "逆PO→上昇PO転換",
    "逆PO転換準備",
    "初動75GC200シグナル",
    "押し目候補シグナル",
    "押し目スコア",
    "PO形成からの日数",
    "75日GC200からの日数",
    "25日線乖離(%)",
    "75日線乖離(%)",
    "200日線乖離(%)",
    "25日線タッチ",
    "75日線タッチ",
    "25日線上で引け",
    "75日線上で引け",
    "下落出来高急増",
    "逆PO履歴あり",
    "PO形成(当日)",
    "PO形成(直近厳選)",
    "PO形成(直近)",
    "25日GC75(直近)",
    "25日GC200(直近厳選)",
    "75日GC200(直近厳選)",
    "総合スコア",
    "トレンドスコア",
    "業績スコア",
    "強さスコア",
    "終値",
    "売買代金(百万円)",
    "時価総額(十億円)",
    "売上成長率(%)",
    "利益率(%)",
    "ROE(%)",
    "20日騰落率(%)",
    "60日騰落率(%)",
    "52週高値差(%)",
    "出来高倍率(20日)",
    "25日線傾き(%)",
    "75日線傾き(%)",
    "25日線>75日線",
    "25日線>200日線",
    "75日線>200日線",
    "PO(25>75>200)",
    "セクター",
    "業種",
]

TRACKING_COLUMN_LABELS = {
    "generated_at": "生成日時",
    "ticker": "ティッカー",
    "name": "銘柄名",
    "entry_date": "取得日",
    "entry_price": "取得単価",
    "adjusted_entry_price": "補正後取得単価",
    "position_type": "種別",
    "close": "終値",
    "close_vs_entry_pct": "取得単価比(%)",
    "close_vs_ma25_pct": "25日線乖離(%)",
    "close_vs_ma75_pct": "75日線乖離(%)",
    "close_vs_ma200_pct": "200日線乖離(%)",
    "ma25_vs_ma75_pct": "25日線-75日線差(%)",
    "ma75_vs_ma200_pct": "75日線-200日線差(%)",
    "change_20d_pct": "20日騰落率(%)",
    "change_60d_pct": "60日騰落率(%)",
    "drawdown_from_60d_high_pct": "60日高値からの下落率(%)",
    "volume_ratio_20": "出来高倍率(20日)",
    "upper_shadow_pct": "上ヒゲ率(%)",
    "status": "判定",
    "status_score": "警戒スコア",
    "suggested_action": "推奨アクション",
    "data_issue": "データ注意",
    "warning_flags": "警戒サイン",
    "note": "メモ",
}

TRACKING_COLUMN_ORDER = [
    "判定",
    "警戒スコア",
    "ティッカー",
    "銘柄名",
    "種別",
    "取得日",
    "取得単価",
    "補正後取得単価",
    "終値",
    "取得単価比(%)",
    "25日線乖離(%)",
    "75日線乖離(%)",
    "200日線乖離(%)",
    "25日線-75日線差(%)",
    "75日線-200日線差(%)",
    "20日騰落率(%)",
    "60日騰落率(%)",
    "60日高値からの下落率(%)",
    "出来高倍率(20日)",
    "上ヒゲ率(%)",
    "推奨アクション",
    "データ注意",
    "警戒サイン",
    "メモ",
    "生成日時",
]


def _apply_order(df: pd.DataFrame, ordered_labels: list[str]) -> pd.DataFrame:
    ordered_existing = []
    seen = set()
    for col in ordered_labels:
        if col in df.columns and col not in seen:
            ordered_existing.append(col)
            seen.add(col)
    remaining = [col for col in df.columns if col not in ordered_existing]
    return df[ordered_existing + remaining]


def format_long_term_output(df: pd.DataFrame) -> pd.DataFrame:
    display_df = df.rename(columns=COLUMN_LABELS)
    return _apply_order(display_df, WATCHLIST_HISTORY_COLUMN_ORDER)


def format_long_term_latest_output(df: pd.DataFrame) -> pd.DataFrame:
    display_df = df.rename(columns=COLUMN_LABELS)
    return display_df[[col for col in WATCHLIST_LATEST_COLUMN_ORDER if col in display_df.columns]]


def format_long_term_gc_output(df: pd.DataFrame) -> pd.DataFrame:
    display_df = df.rename(columns=COLUMN_LABELS)
    return _apply_order(display_df, GC_WATCHLIST_COLUMN_ORDER)


def format_long_term_tracking_output(df: pd.DataFrame) -> pd.DataFrame:
    display_df = df.rename(columns=TRACKING_COLUMN_LABELS)
    return _apply_order(display_df, TRACKING_COLUMN_ORDER)
